name: poker_frontend

description: A simple web interface for the poker service.

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  grpc: ^3.2.0
  protobuf: ^3.1.0
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0

# additional dependencies for UI, state management, etc.

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
